database:
  host: "mysql-database.cvz0vt1mykn7.us-east-2.rds.amazonaws.com"
  user: "admin"
  password: "edgerunners"
  database: "music"
  port: "3306"

data:
  features: "./data/music_features.csv"

s3:
  base_url: "https://xpu7xvvdcg.execute-api.us-east-2.amazonaws.com/dev/aws-music-upload/"
  api_key: "YE8iRuDxUl9Dsrgv4YSYw2N78epi6fIeQaG18OUj"