AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 500
    MemorySize: 2048
  Api:
    Cors:
      AllowMethods: "'POST, OPTION'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  Analyze:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /analyze
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./analyze
      DockerTag: python3.11-v1
  Recommend:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /recommend
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./recommend
      DockerTag: python3.11-v1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AnalyzeApi:
    Description: API Gateway endpoint URL for dev stage for Analyze function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/analyze/"
  Analyze:
    Description: Analyze Lambda Function ARN
    Value: !GetAtt Analyze.Arn
  AnalyzeIamRole:
    Description: Implicit IAM Role created for analyze function
    Value: !GetAtt AnalyzeRole.Arn
  RecommendApi:
    Description: API Gateway endpoint URL for dev stage for Recommend function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/recommend/"
  Recommend:
    Description: Recommend Lambda Function ARN
    Value: !GetAtt Recommend.Arn
  RecommendIamRole:
    Description: Implicit IAM Role created for recommend function
    Value: !GetAtt RecommendRole.Arn
